site_name: dbt Course
site_description: Practical dbt course
site_author: Thiago Oliveira
site_url: https://tjsoliveira.github.io/dbt_course

# Repository
repo_name: tjsoliveira/dbt_course
repo_url: https://github.com/tjsoliveira/dbt_course
edit_uri: edit/main/docs/

# Theme
theme:
  name: material
  language: en
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate
  palette:
    - scheme: default
      primary: teal
      accent: cyan
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - scheme: slate
      primary: teal
      accent: cyan
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

# Navigation
nav:
  - Home: index.md
  - Introduction:
    - What is dbt: intro/what-is-dbt.md
    - Setup: intro/setup.md
    - First Project: intro/first-project.md
  - About the Project:
    - Overview: jaffle-shop/overview.md
    - Project Setup: jaffle-shop/project-setup.md
  - Course:
    - Overview: course/index.md
    - Sources: course/sources.md
    - Models: course/models.md
    - Tests: course/tests.md

# Plugins
plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
      enable_git_follow: false
  - minify:
      minify_html: true

# Extras
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/tjsoliveira/dbt_course
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/tjsoliveira

# Configurações de markdown
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - meta
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - toc:
      anchorlink: true
      permalink: true
