jaffle_shop:
  target: dev
  outputs:
    dev:
      type: sqlite
      threads: 1
      database: 'jaffle_shop'
      schema: 'main'
      schemas_and_paths:
        main: './jaffle_shop/db/jaffle_shop.db'
      schema_directory: 'jaffle_shop'
